apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-tutor
  namespace: ns-tutor
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tutor
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60