apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-quiz
  namespace: ns-quiz
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: quiz
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60