spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  application:
    name: shop
  datasource:
    password: ENC(6hVGR8znYyGzwM+aySVNzGoVtkZ1tlwn) #root
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(ZQuCgoV2wdMB1sXqLSFK3w==) #root
    url:  ENC(lFoVZMV9AX88aF7JETsPuKp07+p4M3mG0h7DDAh19mrlbLjPQ2p6dQ==) #jdbc:mysql://localhost:3306/shop