spring:
  application:
    name: quiz
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(Ii2iWdwoHy/cPCb3capZnQ==)
    password: ENC(fIhh5f7s+JzyXVV2rtVmAD3FdQVboJs1)
    url: ENC(doY8TC499i7z6COMrgMNkVuu3unf20DVdT+6HKSRJvn/K2HXy3TW7Q==)
  jpa:
    hibernate:
      ddl-auto: update