services:
  spring:
    container_name: spring
    image: spring:0.1
    build:
      context: ../backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - AWS_ACCESSKEY=${AWS_ACCESSKEY}
      - AWS_SECRETKEY=${AWS_SECRETKEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - TZ=Asia/Seoul
      - JAVA_OPTS=-Duser.timezone=Asia/Seoul
    networks:
      - my_network

networks:
  my_network:
    external: true