spring:
  application:
    name: tutor
  ai:
    openai:
      api-key: ENC(qQgeVSNiTRTy7EXkRoUowz+DU08I7fSzonxGSwDJ0sVgBft8nY1ffRbfDOHlyX6iHsghvcqO/uAa731eEN+ejPK6hKklmoMlL6HGzl7ef/dvSM4/FnLkcWXoDd7mWU8T8t3Nj+F/ebxtBOmx6tbmWAPAMszgzwNi29eZR77VEdx4XcmVoMSHAGREwfS0V8Ql)
      chat:
        options:
          model: gpt-4o-2024-08-06
          temperature: 0

  datasource:
    url: ENC(ND7ataPAw3IQRTlkDQ5m/rGseS+B8SXNqxugUiCkwUyfzkUxRxFpWA==)
    username: ENC(QwnUyIfu2THVsYXlzD2sow==)
    password: ENC(SOefXdn69nfyCpO4F6b8PSyBEKZhuFZs)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
  data:
    redis:
      lettuce:
        pool:
          max-active: 10
          min-idle: 2
          max-idle: 10
      url: ENC(PpYupva6u0bHkxayZxwBfsuNxK6/OzveFS0Z+KnXUVA=)
etri:
  api:
    key: ENC(A6Zn4InhzjmnNBLUe+bM0+bYos6GMMM98ixjXoYPZJFwIcoGuKusU9MKhF+NjShp)
