apiVersion: v1
kind: Namespace
metadata:
  name: ns-rank
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
  namespace: ns-rank
  labels:
    app: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: "worker"
      containers:
      - name: scheduler
        image: tkdqja9573/ssafy-tailored-scheduler
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: jasypt.encryptor.password
          value: "jenkins_will_set_this"
        resources:
          requests:
            cpu: "200m"
          limits:
            cpu: "400m"
---
apiVersion: v1
kind: Service
metadata:
  name: scheduler
  namespace: ns-rank
  labels:
    app: scheduler
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: scheduler
  type: ClusterIP