server:
  port: 8080

spring:
  application:
    name: alcoholic

  messages:
    encoding: UTF-8

  profiles:
    active: prod

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB
  
  jwt:
    secret: "vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb"

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

# Swagger 설정 추가 (http://localhost:8080/swagger-ui/index.html)
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs